### ISSUE TITLE
Balnk page because of page-break trough CSS

### ISSUE THREAD

**Issue by yveveke** [iclems/iOS-htmltopdf#26]
I don't know if the bug is in uiwebview or in this library. But I've put div's in my html-code with a class pagebreak. It does a page break, but with an extra blank page.
How do I get rid of the blank page.

``` css

    @media all {
        .pagebreak  { display: none; }
    }

    @media print {
        .pagebreak  { display: block; page-break-before: always; }
    }
```
